apiVersion: v1
kind: Pod
metadata:
 labels:
   name: node-mongo
 name: busmeme
spec:
   containers:
   - image: mongo
     name: mongo
     ports:
     - name: mongo
       containerPort: 27017
       hostPort: 27017
   - image: minillinim/busmemegenerator
     name: web
     env:
     - name: NODE_ENV
       value: "production"
     - name: TL_USER
       value: "uSERnAME"
     - name: TL_PASSWORD
       value: "pASSwORD"
     - name: PORT
       value: "80"
     - name: BM_MONGODB_URI
       value: "mongodb://localhost/app-toto"
     - name: BM_ADMIN_TOKEN
       value: "test"
   volumes:
     - name: mongo-persistent-storage
       emptyDir: {}
       volumeMounts:
         - name: mongo-persistent-storage
           mountPath: /data/db
   ports:
     - hostPort: 80
       containerPort: 80
       name: http-server
